---
- name: "set up zabbix ubuntu repo"
  apt_repository: repo="deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
                  state=present

- name: "set up zabbix ubuntu src repo"
  apt_repository: repo="deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
                  state=present

- name: "Install gpg key"
  apt_key: id=79EA5ED4
           url=http://repo.zabbix.com/zabbix-official-repo.key

# Run the equivalent of "apt-get update" as a separate step
- apt: update_cache=yes

- name: "Install zabbix-server package"
  apt: pkg=zabbix-server-mysql
       state=present

- name: "Install zabbix-web"
  apt:  pkg=zabbix-frontend-php
        state=present

- name: "Configure zabbix-server"
  template: src=etc/zabbix/zabbix_server.conf.j2
            dest=/etc/zabbix/zabbix_server.conf
            owner=zabbix
            group=zabbix
            mode=0755
  notify: restart zabbix-server


- name: "Create include dir zabbix-server"
  file: path={{ server_include }}
        owner=zabbix
        group=zabbix
        state=directory

- name: "Configure zabbix-web"
  template: src=etc/zabbix/zabbix.conf.php.j2
            dest=/etc/zabbix/web/zabbix.conf.php
            owner=zabbix
            group=zabbix
            mode=0755

- name: "install apache vhost"
  template: src=apache_vhost.conf.j2
            dest=/etc/apache2/sites-enabled/zabbix.conf
            owner=root
            group=root
            mode=0644
  notify: restart apache2

- name: "zabbix database initialization"
  include: zabbix-database-init.yml
  tags: zabbix-database-init
