---

- name: "Create zabbix database"
  mysql_db: name={{ server_dbname }}
            state=present
            encoding=utf8
            collation=utf8_bin

- name: "Create zabbix database user"
  mysql_user: name={{ server_dbuser }}
              password={{ server_dbpassword }}
              priv={{ server_dbname }}.*:ALL
              state=present

- name: initialize zabbix database
  mysql_db: name={{ server_dbname }} state=import target=/usr/share/zabbix-server-mysql/{{ item }}
  with_items:
    - schema.sql
    - images.sql
    - data.sql

- name: copy sql scripts for database partitioning
  copy: src=tmp/{{ item }} dest=/tmp
  with_items:
    - alter_table_indexes.sql
    - stored_procedures.sql
    - event_schedule.sql

- name: alter table indexes
  mysql_db: name={{ server_dbname }} state=import target=/tmp/alter_table_indexes.sql

- name: add stored procedures for partitioning
  mysql_db: name={{ server_dbname }} state=import target=/tmp/stored_procedures.sql

- name: add partitioning event to schedule
  mysql_db: name={{ server_dbname }} state=import target=/tmp/event_schedule.sql
